<?php
/**
 * HistoryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.9.7-SNAPSHOT
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * HistoryApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HistoryApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addItem
     *
     * Add history item.
     *
     */
    public function testAddItem()
    {
    }

    /**
     * Test case for callList
     *
     * DEPRECATED - List history.
     *
     */
    public function testCallList()
    {
    }

    /**
     * Test case for filteredList
     *
     * List history.
     *
     */
    public function testFilteredList()
    {
    }

    /**
     * Test case for retrieveItem
     *
     * Get history item.
     *
     */
    public function testRetrieveItem()
    {
    }

    /**
     * Test case for updateItem
     *
     * Update history item.
     *
     */
    public function testUpdateItem()
    {
    }

    /**
     * Test case for updateItemVisibility
     *
     * Set history item visibility.
     *
     */
    public function testUpdateItemVisibility()
    {
    }
}
