<?php
/**
 * PublicServicesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ID4i API
 *
 * HTTP API Documentation for ID4i
 *
 * OpenAPI spec version: 0.1.5-SNAPSHOT
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.2.3
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * PublicServicesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PublicServicesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getPublicDocument
     *
     * Retrieve a document (meta-data only, no content).
     *
     */
    public function testGetPublicDocument()
    {
    }

    /**
     * Test case for getPublicDocument1
     *
     * Retrieve a document (meta-data only, no content).
     *
     */
    public function testGetPublicDocument1()
    {
    }

    /**
     * Test case for go
     *
     * Forward.
     *
     */
    public function testGo()
    {
    }

    /**
     * Test case for listAllPublicDocuments
     *
     * List organization specific documents.
     *
     */
    public function testListAllPublicDocuments()
    {
    }

    /**
     * Test case for listAllPublicDocuments1
     *
     * List organization specific documents.
     *
     */
    public function testListAllPublicDocuments1()
    {
    }

    /**
     * Test case for listPublicDocuments
     *
     * List organization specific documents.
     *
     */
    public function testListPublicDocuments()
    {
    }

    /**
     * Test case for listPublicDocuments1
     *
     * List organization specific documents.
     *
     */
    public function testListPublicDocuments1()
    {
    }

    /**
     * Test case for readPublicDocument
     *
     * Read document contents.
     *
     */
    public function testReadPublicDocument()
    {
    }

    /**
     * Test case for readPublicDocument1
     *
     * Read document contents.
     *
     */
    public function testReadPublicDocument1()
    {
    }

    /**
     * Test case for resolveImageUsingGET
     *
     * Resolve image.
     *
     */
    public function testResolveImageUsingGET()
    {
    }

    /**
     * Test case for resolveWhoIsEntry
     *
     * Resolve owner of id4n.
     *
     */
    public function testResolveWhoIsEntry()
    {
    }
}
