<?php
/**
 * GuidTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bluerain\ID4iClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 1.0.1-SNAPSHOT
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Bluerain\ID4iClient;

/**
 * GuidTest Class Doc Comment
 *
 * @category    Class */
// * @description Guid
/**
 * @package     Bluerain\ID4iClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GuidTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Guid"
     */
    public function testGuid()
    {
    }

    /**
     * Test attribute "created_timestamp"
     */
    public function testPropertyCreatedTimestamp()
    {
    }

    /**
     * Test attribute "holder_organization_id"
     */
    public function testPropertyHolderOrganizationId()
    {
    }

    /**
     * Test attribute "id4n"
     */
    public function testPropertyId4n()
    {
    }

    /**
     * Test attribute "owner_organization_id"
     */
    public function testPropertyOwnerOrganizationId()
    {
    }

    /**
     * Test attribute "physical_state"
     */
    public function testPropertyPhysicalState()
    {
    }

    /**
     * Test attribute "properties"
     */
    public function testPropertyProperties()
    {
    }
}
