<?php
/**
 * HistoryItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bluerain\ID4iClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 0.9.7
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Bluerain\ID4iClient;

/**
 * HistoryItemTest Class Doc Comment
 *
 * @category    Class */
// * @description GUID history item
/**
 * @package     Bluerain\ID4iClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HistoryItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HistoryItem"
     */
    public function testHistoryItem()
    {
    }

    /**
     * Test attribute "additional_properties"
     */
    public function testPropertyAdditionalProperties()
    {
    }

    /**
     * Test attribute "organization_id"
     */
    public function testPropertyOrganizationId()
    {
    }

    /**
     * Test attribute "owner_organization_id"
     */
    public function testPropertyOwnerOrganizationId()
    {
    }

    /**
     * Test attribute "sequence_id"
     */
    public function testPropertySequenceId()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "visibility"
     */
    public function testPropertyVisibility()
    {
    }
}
