<?php
/**
 * ApiKeysApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Bluerain\ID4iClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Bluerain\ID4iClient;

use \Bluerain\ID4iClient\Configuration;
use \Bluerain\ID4iClient\ApiException;
use \Bluerain\ID4iClient\ObjectSerializer;

/**
 * ApiKeysApiTest Class Doc Comment
 *
 * @category Class
 * @package  Bluerain\ID4iClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApiKeysApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addApiKeyPrivilege
     *
     * Add privilege.
     *
     */
    public function testAddApiKeyPrivilege()
    {
    }

    /**
     * Test case for addApiKeyPrivilegeForId4ns
     *
     * Add ID4ns of a privilege.
     *
     */
    public function testAddApiKeyPrivilegeForId4ns()
    {
    }

    /**
     * Test case for createNewApiKey
     *
     * Create API key.
     *
     */
    public function testCreateNewApiKey()
    {
    }

    /**
     * Test case for deleteApiKey
     *
     * Delete API key.
     *
     */
    public function testDeleteApiKey()
    {
    }

    /**
     * Test case for getApiKey
     *
     * Show API key.
     *
     */
    public function testGetApiKey()
    {
    }

    /**
     * Test case for listAllApiKeyPrivileges
     *
     * List all privileges.
     *
     */
    public function testListAllApiKeyPrivileges()
    {
    }

    /**
     * Test case for listAllApiKeysOfOrganization
     *
     * Find API key by organization.
     *
     */
    public function testListAllApiKeysOfOrganization()
    {
    }

    /**
     * Test case for listApiKeyPrivileges
     *
     * List privileges.
     *
     */
    public function testListApiKeyPrivileges()
    {
    }

    /**
     * Test case for listId4ns
     *
     * ID4ns of a privilege.
     *
     */
    public function testListId4ns()
    {
    }

    /**
     * Test case for removeApiKeyPrivilege
     *
     * Remove privilege.
     *
     */
    public function testRemoveApiKeyPrivilege()
    {
    }

    /**
     * Test case for removeApiKeyPrivilegeForId4ns
     *
     * Remove id4ns of a privilege.
     *
     */
    public function testRemoveApiKeyPrivilegeForId4ns()
    {
    }

    /**
     * Test case for updateApiKey
     *
     * Update API keys.
     *
     */
    public function testUpdateApiKey()
    {
    }
}
