<?php
/**
 * MessagingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Bluerain\ID4iClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ID4i API
 *
 * ID4i HTTP API
 *
 * OpenAPI spec version: 1.0.0-SNAPSHOT
 * Contact: info@bluerain.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Bluerain\ID4iClient;

use \Bluerain\ID4iClient\Configuration;
use \Bluerain\ID4iClient\ApiException;
use \Bluerain\ID4iClient\ObjectSerializer;

/**
 * MessagingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Bluerain\ID4iClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessagingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for enqueueCustomMessage
     *
     * Enqueue a custom message.
     *
     */
    public function testEnqueueCustomMessage()
    {
    }

    /**
     * Test case for getDefaultQueue
     *
     * .
     *
     */
    public function testGetDefaultQueue()
    {
    }

    /**
     * Test case for patchDefaultQueue
     *
     * .
     *
     */
    public function testPatchDefaultQueue()
    {
    }
}
